// Галерея встроенных шаблонов страниц
// Каждый шаблон — функция makeElements(w, h) → массив элементов

export const TEMPLATES = [
  {
    id: 'classic-gazette',
    label: 'Городской вестник',
    icon: 'fas fa-newspaper',
    paperStyle: 'classic',
    makeElements: (w, h) => ([
      { id:'tpl_mast',  type:'masthead', x:0,   y:0,   w:w, h:140,
        props:{ line1:'Городской', line2:'Вестник', motto:'"Правда без прикрас"', style:'classic', textColor:'' } },
      { id:'tpl_rule1', type:'rule', x:0, y:143, w:w, h:14,
        props:{ thickness:3, style:'double', color:'#1a1a1a' } },
      { id:'tpl_head',  type:'headline', x:10, y:168, w:Math.round(w*0.66), h:90,
        props:{ text:'Заголовок главной статьи', fontSize:32, fontUnit:'px', textColor:'' } },
      { id:'tpl_byl',   type:'byline',   x:10, y:262, w:Math.round(w*0.66), h:24,
        props:{ text:'Корреспондент: Имя Автора', textColor:'' } },
      { id:'tpl_body',  type:'body',     x:10, y:292, w:Math.round(w*0.66), h:300,
        props:{ text:'Текст первого абзаца статьи...\n\nТекст второго абзаца статьи с продолжением.', fontSize:13, fontUnit:'px', dropCap:true, columns:2, textColor:'' } },
      { id:'tpl_img',   type:'image',    x:10, y:600, w:Math.round(w*0.66), h:180,
        props:{ url:'', caption:'Подпись к иллюстрации', scale:100, borderStyle:'none' } },
      { id:'tpl_quote', type:'quote',    x:Math.round(w*0.7), y:168, w:Math.round(w*0.28), h:160,
        props:{ text:'Важная цитата дня', author:'— Очевидец', textColor:'' } },
      { id:'tpl_box',   type:'box',      x:Math.round(w*0.7), y:338, w:Math.round(w*0.28), h:200,
        props:{ title:'Коротко', text:'Важные новости в двух словах...', border:true, textColor:'' } },
      { id:'tpl_ad',    type:'ad',       x:Math.round(w*0.7), y:548, w:Math.round(w*0.28), h:120,
        props:{ title:'ОБЪЯВЛЕНИЕ', text:'Текст объявления здесь...', textColor:'' } },
    ]),
  },

  {
    id: 'wanted-poster',
    label: 'Разыскивается!',
    icon: 'fas fa-user-secret',
    paperStyle: 'vintage',
    makeElements: (w, h) => {
      const imgSize = Math.round(w * 0.5);
      const imgY = 110;
      return [
        { id:'tpl_want',   type:'masthead', x:0, y:0,   w:w, h:100,
          props:{ line1:'РАЗЫСКИВАЕТСЯ', line2:'', motto:'Живым или мёртвым', style:'classic', textColor:'' } },
        { id:'tpl_img',    type:'image',    x:Math.round(w*0.25), y:imgY, w:imgSize, h:imgSize,
          props:{ url:'', caption:'', scale:100, borderStyle:'double' } },
        { id:'tpl_name',   type:'headline', x:0, y:imgY+imgSize+20, w:w, h:80,
          props:{ text:'Имя Преступника', fontSize:38, fontUnit:'px', textColor:'' } },
        { id:'tpl_reward', type:'headline', x:0, y:imgY+imgSize+110, w:w, h:60,
          props:{ text:'Награда: 500 золотых', fontSize:26, fontUnit:'px', textColor:'#8b2e2e' } },
        { id:'tpl_desc',   type:'body',     x:20, y:imgY+imgSize+180, w:w-40, h:180,
          props:{ text:'Особые приметы: ...\n\nОпасен и вооружён. Приближаться с осторожностью.', fontSize:13, fontUnit:'px', dropCap:false, columns:1, textColor:'' } },
      ];
    },
  },

  {
    id: 'secret-document',
    label: 'Секретный документ',
    icon: 'fas fa-file-alt',
    paperStyle: 'archive',
    makeElements: (w, h) => ([
      { id:'tpl_stamp', type:'masthead', x:0, y:0, w:w, h:110,
        props:{ line1:'СОВЕРШЕННО', line2:'СЕКРЕТНО', motto:'Уничтожить после прочтения', style:'classic', textColor:'#8b0000' } },
      { id:'tpl_rule1', type:'rule', x:0, y:113, w:w, h:10,
        props:{ thickness:2, style:'solid', color:'#8b0000' } },
      { id:'tpl_head',  type:'headline', x:20, y:134, w:w-40, h:70,
        props:{ text:'ДЕЛО № 0042 — Операция «Тёмный Горизонт»', fontSize:22, fontUnit:'px', textColor:'#333' } },
      { id:'tpl_byl',   type:'byline',   x:20, y:208, w:w-40, h:24,
        props:{ text:'Составлено: Отдел разведки | Дата: ' + new Date().toLocaleDateString(), textColor:'' } },
      { id:'tpl_rule2', type:'rule', x:0, y:235, w:w, h:8,
        props:{ thickness:1, style:'dashed', color:'#555' } },
      { id:'tpl_body',  type:'body',     x:20, y:250, w:w-40, h:400,
        props:{ text:'1. ЦЕЛЬ ОПЕРАЦИИ\nОписание цели операции...\n\n2. ИСПОЛНИТЕЛИ\nСписок лиц, задействованных в операции...\n\n3. ПРИМЕЧАНИЯ\nДополнительные сведения...', fontSize:13, fontUnit:'px', dropCap:false, columns:1, textColor:'' } },
      { id:'tpl_box',   type:'box',      x:20, y:660, w:w-40, h:100,
        props:{ title:'ПРЕДУПРЕЖДЕНИЕ', text:'Распространение данного документа карается по законам Империи.', border:true, textColor:'#8b0000' } },
    ]),
  },

  {
    id: 'cyber-report',
    label: 'Технический отчёт',
    icon: 'fas fa-terminal',
    paperStyle: 'cyber',
    makeElements: (w, h) => ([
      { id:'tpl_mast', type:'masthead', x:0, y:0, w:w, h:120,
        props:{ line1:'NEXUS', line2:'REPORT', motto:'// CLASSIFIED TRANSMISSION //', style:'classic', textColor:'#00ff88' } },
      { id:'tpl_rule1', type:'rule', x:0, y:123, w:w, h:8,
        props:{ thickness:2, style:'solid', color:'#00ff88' } },
      { id:'tpl_head', type:'headline', x:10, y:140, w:w-20, h:70,
        props:{ text:'ОПЕРАЦИЯ: КОД КРАСНЫЙ — СТАТУС АКТИВЕН', fontSize:20, fontUnit:'px', textColor:'#00ff88' } },
      { id:'tpl_byl',  type:'byline',   x:10, y:215, w:w-20, h:24,
        props:{ text:'ИСТОЧНИК: АГЕНТ-7 | ВРЕМЕННАЯ МЕТКА: ' + Date.now(), textColor:'#888' } },
      { id:'tpl_body', type:'body',     x:10, y:248, w:Math.round(w*0.58), h:340,
        props:{ text:'СТАТУС МИССИИ: АКТИВНА\n\nЦЕЛЕВОЙ ОБЪЕКТ обнаружен в секторе Дельта-9. Наблюдение установлено.\n\nПРОТОКОЛ ДЕЙСТВИЙ:\nФаза 1 — сбор данных завершена\nФаза 2 — инфильтрация в процессе\nФаза 3 — ожидание подтверждения', fontSize:12, fontUnit:'px', dropCap:false, columns:1, textColor:'#cccccc' } },
      { id:'tpl_box1', type:'box',      x:Math.round(w*0.62), y:248, w:Math.round(w*0.36), h:160,
        props:{ title:'// ДАННЫЕ ЦЕЛИ', text:'Идентификатор: UNKNOWN\nУгроза: ВЫСОКАЯ\nМестоположение: АКТИВНО', border:true, textColor:'#00ff88' } },
      { id:'tpl_box2', type:'box',      x:Math.round(w*0.62), y:420, w:Math.round(w*0.36), h:160,
        props:{ title:'// РЕСУРСЫ', text:'Агентов в поле: 3\nРезервная группа: ГОТОВА\nЭвакуация: ПЛАН Б', border:true, textColor:'#ffaa00' } },
    ]),
  },

  {
    id: 'royal-proclamation',
    label: 'Королевский указ',
    icon: 'fas fa-crown',
    paperStyle: 'luxury',
    makeElements: (w, h) => ([
      { id:'tpl_rule0', type:'rule', x:20, y:20, w:w-40, h:12,
        props:{ thickness:3, style:'double', color:'#8b6914' } },
      { id:'tpl_mast', type:'masthead', x:0, y:40, w:w, h:160,
        props:{ line1:'КОРОЛЕВСКИЙ', line2:'УКАЗ', motto:'Именем Его Величества', style:'classic', textColor:'#5c3d0a' } },
      { id:'tpl_rule1', type:'rule', x:20, y:205, w:w-40, h:12,
        props:{ thickness:3, style:'double', color:'#8b6914' } },
      { id:'tpl_head', type:'headline', x:40, y:228, w:w-80, h:80,
        props:{ text:'О порядке и законе в землях Короны', fontSize:26, fontUnit:'px', textColor:'#3d2000' } },
      { id:'tpl_body', type:'body',     x:40, y:318, w:w-80, h:380,
        props:{ text:'Мы, Его Величество, волею Небес Король всех земель наших, в целях сохранения мира и порядка сим указом повелеваем:\n\n§ 1. Всем подданным надлежит...\n\n§ 2. Нарушители сего указа...\n\n§ 3. Настоящий указ вступает в силу немедленно.', fontSize:13, fontUnit:'px', dropCap:true, columns:1, textColor:'#2a1500' } },
      { id:'tpl_rule2', type:'rule', x:20, y:710, w:w-40, h:10,
        props:{ thickness:2, style:'double', color:'#8b6914' } },
      { id:'tpl_byl',  type:'byline', x:40, y:728, w:w-80, h:24,
        props:{ text:'Скреплено печатью Королевской канцелярии. Год правления 1347.', textColor:'#5c3d0a' } },
      { id:'tpl_rule3', type:'rule', x:20, y:760, w:w-40, h:12,
        props:{ thickness:3, style:'double', color:'#8b6914' } },
    ]),
  },

  {
    id: 'news-flash',
    label: 'Срочно в номер',
    icon: 'fas fa-bolt',
    paperStyle: 'noir',
    makeElements: (w, h) => ([
      { id:'tpl_flash', type:'masthead', x:0, y:0, w:w, h:100,
        props:{ line1:'⚡ СРОЧНО', line2:'В НОМЕР', motto:'Экстренный выпуск', style:'classic', textColor:'#ffffff' } },
      { id:'tpl_rule1', type:'rule', x:0, y:103, w:w, h:10,
        props:{ thickness:4, style:'solid', color:'#ffffff' } },
      { id:'tpl_head', type:'headline', x:10, y:122, w:w-20, h:130,
        props:{ text:'ГЛАВНЫЙ ЗАГОЛОВОК ЭКСТРЕННОГО ВЫПУСКА', fontSize:40, fontUnit:'px', textColor:'#ffffff' } },
      { id:'tpl_rule2', type:'rule', x:0, y:258, w:w, h:8,
        props:{ thickness:2, style:'solid', color:'#888' } },
      { id:'tpl_body', type:'body',     x:10, y:272, w:Math.round(w*0.72), h:300,
        props:{ text:'Кратко о произошедшем: место, время, обстоятельства.\n\nПодробности выясняются. Наш корреспондент на месте событий сообщает...', fontSize:14, fontUnit:'px', dropCap:true, columns:1, textColor:'#dddddd' } },
      { id:'tpl_box', type:'box',       x:Math.round(w*0.75), y:272, w:Math.round(w*0.23), h:200,
        props:{ title:'ФАКТЫ', text:'Что известно:\n• Пункт 1\n• Пункт 2\n• Пункт 3', border:true, textColor:'#ffffff' } },
      { id:'tpl_byl', type:'byline',    x:10, y:580, w:w-20, h:24,
        props:{ text:'Специальный корреспондент | Редакция работает круглосуточно', textColor:'#888' } },
    ]),
  },
];
